"""
CodeLens RAG — Precision@5 scorer.

Computes mean Precision@5 over a set of retrieval questions.
Supports ±2-line tolerance when comparing chunk identifiers.
Scores range from 0.0 to 1.0 per question.

Usage:
    python score.py --predictions results.json --questions eval_questions.json

Where:
    results.json      — file generated by the team's RAG system (see format below)
    eval_questions.json — ground-truth questions file (provided in the dataset)

results.json format:
    [
        {
            "question_id": "q_01",
            "top_5_chunks": [
                "gymhero/security.py:create_access_token:12",
                "gymhero/api/dependencies.py:get_token:35",
                "gymhero/config.py:Settings:11",
                "gymhero/exceptions.py:_get_credential_exception:5",
                "gymhero/main.py:root:33"
            ]
        },
        ...
    ]

Exit codes:
    0 — scoring completed successfully
    1 — input format error or missing file
"""

import argparse
import json
import sys
from pathlib import Path
from collections import defaultdict


def parse_chunk_id(chunk_id: str):
    """Parse a chunk_id string into (path, name, lineno).

    Returns None if the chunk_id does not have the expected format.
    """
    parts = chunk_id.rsplit(":", 2)
    if len(parts) != 3:
        return None
    path, name, line_str = parts
    try:
        lineno = int(line_str)
    except ValueError:
        return None
    return path, name, lineno


def chunks_match(predicted: str, reference: str, tolerance: int = 2) -> bool:
    """Return True if predicted chunk_id matches reference within ±tolerance lines.

    Matching rules:
        - path must be identical (case-sensitive)
        - name must be identical (case-sensitive)
        - start_line difference must be <= tolerance
    """
    p = parse_chunk_id(predicted)
    r = parse_chunk_id(reference)
    if p is None or r is None:
        return False
    p_path, p_name, p_line = p
    r_path, r_name, r_line = r
    return (p_path == r_path and p_name == r_name and abs(p_line - r_line) <= tolerance)


def score_question(top5: list[str], correct: list[str]) -> float:
    """Compute Precision@5 for a single question.

    Formula: matched / min(5, len(correct))

    This normalizes the score so that finding all reference chunks
    yields 1.0 regardless of how many references the question has.

    Examples:
        1 reference, 1 found in top-5  → 1.0
        2 references, 2 found          → 1.0
        3 references, 2 found          → 0.67
        3 references, 0 found          → 0.0
    """
    if len(correct) == 0:
        print("ERROR: question has no correct_chunk_ids.", file=sys.stderr)
        sys.exit(1)

    # Deduplicate while preserving order
    seen = []
    for chunk in top5:
        if chunk not in seen:
            seen.append(chunk)
    top5_dedup = seen

    matched = 0
    used_refs = set()
    for pred in top5_dedup:
        for i, ref in enumerate(correct):
            if i not in used_refs and chunks_match(pred, ref):
                matched += 1
                used_refs.add(i)
                break

    return matched / min(5, len(correct))


def load_json(path: Path, label: str) -> list | None:
    """Load and parse a JSON file; return None on error."""
    if not path.exists():
        print(f"ERROR: {label} file not found: {path}", file=sys.stderr)
        return None
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as e:
        print(f"ERROR: {label} is not valid JSON: {e}", file=sys.stderr)
        return None
    if not isinstance(data, list):
        print(f"ERROR: {label} must be a JSON array.", file=sys.stderr)
        return None
    return data


def main() -> int:
    parser = argparse.ArgumentParser(
        description="CodeLens RAG — Precision@5 scorer"
    )
    parser.add_argument(
        "--predictions", required=True,
        help="Path to results.json generated by the team's RAG system"
    )
    parser.add_argument(
        "--questions", required=True,
        help="Path to eval_questions.json (ground-truth)"
    )
    args = parser.parse_args()

    predictions_path = Path(args.predictions)
    questions_path = Path(args.questions)

    predictions_raw = load_json(predictions_path, "predictions")
    if predictions_raw is None:
        return 1

    questions_raw = load_json(questions_path, "questions")
    if questions_raw is None:
        return 1

    # Build ground-truth index
    gt: dict[str, dict] = {}
    for q in questions_raw:
        if not isinstance(q, dict):
            print("ERROR: each question entry must be a JSON object.", file=sys.stderr)
            return 1
        qid = q.get("question_id")
        if not qid:
            print("ERROR: question missing 'question_id'.", file=sys.stderr)
            return 1
        gt[qid] = q

    # Build predictions index
    pred_index: dict[str, list[str]] = {}
    for entry in predictions_raw:
        if not isinstance(entry, dict):
            print("ERROR: each prediction entry must be a JSON object.", file=sys.stderr)
            return 1
        qid = entry.get("question_id")
        top5 = entry.get("top_5_chunks", [])
        if not qid:
            print("ERROR: prediction entry missing 'question_id'.", file=sys.stderr)
            return 1
        if not isinstance(top5, list):
            print(f"ERROR: top_5_chunks for {qid} must be a list.", file=sys.stderr)
            return 1
        if len(top5) < 5:
            print(
                f"WARNING: {qid} has only {len(top5)} chunk(s) in top_5_chunks "
                f"(expected 5). Scoring as-is."
            )
        pred_index[qid] = top5

    # Score each question
    per_question: list[dict] = []
    missing_preds = []

    for qid, q in gt.items():
        correct = q.get("correct_chunk_ids", [])
        difficulty = q.get("difficulty", "unknown")
        language = q.get("language", "unknown")

        if qid not in pred_index:
            print(
                f"WARNING: no prediction found for {qid}. Scoring as 0."
            )
            missing_preds.append(qid)
            score = 0.0
        else:
            score = score_question(pred_index[qid], correct)

        per_question.append({
            "question_id": qid,
            "difficulty": difficulty,
            "language": language,
            "n_correct": len(correct),
            "score": score,
        })

    if not per_question:
        print("ERROR: no questions to score.", file=sys.stderr)
        return 1

    # Aggregate
    total = len(per_question)
    mean_score = sum(r["score"] for r in per_question) / total

    # By difficulty
    by_difficulty: dict[str, list[float]] = defaultdict(list)
    for r in per_question:
        by_difficulty[r["difficulty"]].append(r["score"])

    # By language
    by_language: dict[str, list[float]] = defaultdict(list)
    for r in per_question:
        by_language[r["language"]].append(r["score"])

    # Output
    print("=== CodeLens RAG -- Scoring ===")
    print()
    print(f"Questions evaluated: {total}")
    print(f"Mean Precision@5: {mean_score:.3f}")
    print()
    print("By difficulty:")
    for diff in ["easy", "medium", "hard"]:
        scores = by_difficulty.get(diff, [])
        if scores:
            avg = sum(scores) / len(scores)
            print(f"  {diff:<8} {avg:.3f} ({len(scores)} questions)")
    print()
    print("By language:")
    for lang in ["ru", "en"]:
        scores = by_language.get(lang, [])
        if scores:
            avg = sum(scores) / len(scores)
            print(f"  {lang}: {avg:.3f} ({len(scores)} questions)")
    print()
    print("Per-question detail:")
    for r in sorted(per_question, key=lambda x: x["question_id"]):
        n = r["n_correct"]
        s = r["score"]
        matched_count = round(s * min(5, r["n_correct"]))
        print(
            f"  {r['question_id']} [{r['difficulty']}, {r['language']}]"
            f" -- {matched_count}/{n} expected in top-5 -> {s:.2f}"
        )
    print()
    print(f"Total score: {mean_score:.3f}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
